### ISSUE TITLE
Huddle Permissions page "error"

### ISSUE THREAD

**Issue by Quevin** [uwmweb/uwmcms#64]
Hi @briantschu , this may need to be a ticket to Acquia to figure it out because there's nothing in the logs to explain it.

- http://huddle.cms.uwmedicine.org/admin/people/permissions

> Temporarily Unavailable
> The website that you're trying to reach is having technical difficulties and is currently unavailable.
> We are aware of the issue and are working hard to fix it. Thank you for your patience.

It's likely related to all the roles that Ligntning included, which we're not using, and we only need "UWM Editor" role.

I can get to http://huddle.cms.uwmedicine.org/admin/people/permissions/uwm_editor to do what I need to do for Karen's team to proceed with content editing. It's just the main permissions page that would show those other roles that bugs out.

Thank you

**Comment by briantschu** [comment]
Hi @Quevin, it looks like this is an out of memory error.

```
[20-Jul-2017 11:32:18 America/Los_Angeles] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4491613 bytes) in /mnt/www/html/uwmed/docroot/core/lib/Drupal/Component/Render/MarkupTrait.php on line 38 request_id="v-b82abc04-6d79-11e7-ada4-065160dc2f9e"
```

I tested this locally (where my memory limit is higher) and confirmed the page eventually loaded, though it's slow.

You're right, after deleting the additional Lightning roles the page loaded much more quickly.

There's a configuration setting available to turn off the auto-creation of Lightning roles, but when I visit the [Lightning configuration page](http://huddle.cms.uwmedicine.org/admin/config/system/lightning), I get an access denied page. Do you know what is causing this? Is it because some of the Lightning modules are disabled?
